version: '3.8'
services:
    app:
        build:
            dockerfile: Dockerfile
        depends_on:
            - postgres
        volumes:
            - ./:/usr/src/app/
            - '/usr/src/app/node_modules'
        ports:
            - "8080:8080"
    postgres:
        image: postgres:14.1-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres
        volumes:
            - './init:/docker-entrypoint-initdb.d/'
