version: '3.8'
services:
    app:
        build: .
        depends_on:
            - postgres
        ports:
            - "8080:8080"
        volumes:
            - ./:/usr/src/app/
    postgres:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        volumes:
            - './init:/docker-entrypoint-initdb.d/'